name: Continuous Integration
on:
    pull_request:
        branches: 
          - main
jobs:
    tests:
        runs-on: ubuntu-latest
        steps:             
        -  
            name: Git Checkout 
            uses: actions/checkout@v4 
 
        -   name: Setup .NET Core SDK
            uses: actions/setup-dotnet@v4
            with:
                dotnet-version: '8.0'     
              
        -   name: Restore Dependencies
            run: dotnet restore Fiap.Web.SmartWasteManagement.sln

        -   name: Build solution
            run: dotnet build Fiap.Web.SmartWasteManagement.sln --configuration Release --no-restore

        -   name: Run Tests
            run: dotnet test Fiap.Web.SmartWasteManagement.sln --no-restore --verbosity normal --logger "trx;LogFileName=test_results.trx"


