name: Continuous Delivery

on:
    push:
        branches: 
            -   main
 
env:
  IMAGE_NAME: fiap-smartwastemanagement
  AZURE_WEBAPP_NAME: fiap-smart-waste-dev
 
jobs:
    build:
        runs-on: ubuntu-latest
        steps:             
        -  
            name: Git Checkout 
            uses: actions/checkout@v4 
 
        -   name: Setup .NET Core SDK
            uses: actions/setup-dotnet@v4
            with:
                dotnet-version: '8.0'     

        -   name: Setup Docker Buildx
            uses: docker/setup-buildx-action@v2

        -   name: Login to Docker Hub
            uses: docker/login-action@v3
            with:
                registry: https://index.docker.io/v1/
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

        -   name: Build 
            uses: docker/build-push-action@v6 
            with: 
                push: true
                tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
                file: ./Dockerfile
    deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
        -   name: Deploy to Azure Web App
            id: deploy-to-webapp
            uses: azure/webapps-deploy@v2
            with:
              app-name: ${{ env.AZURE_WEBAPP_NAME }}
              publish-profile: ${{ secrets.AZURE_PROFILE }}
              images: 'index.docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest'