name: Continuous Integration
on:
    pull_request:
        branches: 
          - main
jobs:
    tests:
        runs-on: ubuntu-latest
        steps:             
        -  
            name: Git Checkout 
            uses: actions/checkout@v4 
 
        -   name: Setup .NET Core SDK
            uses: actions/setup-dotnet@v4
            with:
                dotnet-version: '8.0'     
              
        -   name: Test with xUnit
            run: dotnet test Fiap.Web.SmartWasteManagement.Tests.sln --no-build --verbosity normal --logger "trx;LogFileName=test_results.trx"

